server:
    port: 8085

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://192.168.22.137:3306/gobuy?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: gobuy
        password: gobuy
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 192.168.22.141
    rabbitmq:
        host: 192.168.22.141
        username: gobuy
        password: gobuy
        virtual-host: /gobuy

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka
    instance:
        lease-renewal-interval-in-seconds: 5        # 心跳时间
        lease-expiration-duration-in-seconds: 15    # 过期时间

mybatis:
    type-aliases-package: com.gobuy.user.pojo