server:
    port: 8087
spring:
    application:
        name: auth-service
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka
        registry-fetch-interval-seconds: 10
    instance:
        lease-renewal-interval-in-seconds: 5        # 心跳时间
        lease-expiration-duration-in-seconds: 15    # 过期时间


gobuy:
    auth-jwt:
        secret: login@Gobuy(Auth)78&*^31jflkJjfi&23%
        pubKeyPath: D:/tmp/rsa.pub
        priKeyPath: D:\\tmp\\rsa.pri
        expire: 1440  # 过期时间
        cookie-name: user-identity