server:
    port: 8082

spring:
    application:
        name: upload-service

    servlet:
        multipart:
            max-file-size: 5MB


# Eureka
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka

    instance:
        lease-renewal-interval-in-seconds: 5        # 5秒钟发送一次心跳
        lease-expiration-duration-in-seconds: 10    # 10秒过期时间

# FastDFS
fdfs:
    so-timeout: 1501
    connect-timeout: 601
    thumb-image:
        width: 60
        height: 60
    tracker-list:
        - 192.168.22.137:22122