server:
    port: 8081

spring:
    application:
        name: item-service

    datasource:
        url: jdbc:mysql://192.168.22.137/gobuy?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: gobuy
        password: gobuy
        hikari:
            maximum-pool-size: 30
            minimum-idle: 10

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:10086/eureka
    instance:
        lease-renewal-interval-in-seconds: 5        # 心跳时间
        lease-expiration-duration-in-seconds: 15    # 过期时间



